elua: false #Lisence
first-load: true #First load system. If you want to reset all to default change there on false.
defaultUser: #Created users on first load.
  [
    {"Login": "Admin", "Password": "admin"},
    {"Login": "User", Password: "user"}
  ]
max-size-tab: 7 #Max size tab num 16 or change parm database to set a more size -> us_users -> tab_num -> varchar(16).
